#!/bin/bash
# Script to copy files needed to execute baseline audit
# Files are placed at their designated destinations based on the
# default configs of this program.
# Author: Jordan Alexis Caraballo-Vega, University of Puerto Rico at Humacao

# Link to download scap-security-guide
SSG_link="https://github.com/OpenSCAP/scap-security-guide/releases/download/v0.1.38/scap-security-guide-0.1.38-oval-5.10.zip"
SSG_dir="scap-security-guide-0.1.38-oval-5.10"

### Create scap dir in etc for conf file
mkdir -m 600 /etc/scaptest
cp CheckScapStatus.cfg /etc/scaptest/

### Copy files to nagios functions folder
cp CheckBaseScapStatus CheckVulnScapStatus /usr/share/nagios-client/functions/

### Create scap dir in /usr/local/lib for excecutable files

# Baseline Audit Files
mkdir -m 600 /usr/local/lib/scaptest
cp BaseScapTest.pl /usr/local/lib/scaptest/

# Vulnerabilities Audit Files
cp VulnScapTest.pl /usr/local/lib/scaptest/
cp RunBaseScapTest RunVulnScapTest /etc/cron.daily/

# Download and unzip scap-security-guide latest prebuilt from git
mkdir -m 600 /usr/local/src/scaptest
wget $SSG_link -O /usr/local/src/scaptest/scap-security-guide.zip
unzip /usr/local/src/scaptest/scap-security-guide.zip -d /usr/local/src/scaptest
mv /usr/local/src/scaptest/$SSG_dir /usr/local/src/scaptest/scap-security-guide
#-------------------------------------------------------------------------
# Test files
#-------------------------------------------------------------------------
if [ ! -f "/etc/scaptest/CheckScapStatus.cfg" ]; then
	echo "CheckScapStatus.cfg NOT FOUND at destination..."
fi
#-------------------------------------------------------------------------
if [ ! -f "/usr/share/nagios-client/functions/CheckBaseScapStatus" ]; then
	echo "CheckBaseScapStatus NOT FOUND at destination..."
fi
#-------------------------------------------------------------------------
if [ ! -f "/usr/share/nagios-client/functions/CheckVulnScapStatus" ]; then
	echo "CheckVulnScapStatus NOT FOUND at destination..."
fi
#-------------------------------------------------------------------------
if [ ! -f "/usr/local/lib/scaptest/BaseScapTest.pl" ]; then
	echo "BaseScapTest.pl NOT FOUND at destination..."
fi
#-------------------------------------------------------------------------
if [ ! -f "/usr/local/lib/scaptest/VulnScapTest.pl" ]; then
	echo "VulnScapTest.pl NOT FOUND at destination..."
fi
#-------------------------------------------------------------------------
if [ ! -f "/etc/cron.daily/RunBaseScapTest" ]; then
	echo "RunBaseScapTest NOT FOUND at destination..."
fi
#-------------------------------------------------------------------------
if [ ! -f "/etc/cron.daily/RunVulnScapTest" ]; then
	echo "RunVulnScapTest NOT FOUND at destination..."
fi
#-------------------------------------------------------------------------
if [ ! -d "/usr/local/src/scaptest/scap-security-guide" ]; then
	echo "RunVulnScapTest NOT FOUND at destination..."
fi
#-------------------------------------------------------------------------
echo "Done."
